### ISSUE TITLE
Could not find style data in module named shared-styles warning

### ISSUE THREAD

**Issue by 5amfung** [loopingz/webda-tags#1]
When I include `webda-tags.html` in my `elements.html` where my other polymer components are included, I would get the following warning.  Do you have any idea why?

![image](https://cloud.githubusercontent.com/assets/371691/16906292/59aaf102-4c6a-11e6-9028-e41eb42f71d1.png)

**Comment by loopingz** [comment]
Yes I use the yeoman Polymer generator, and there is a module called shared-style to share CSS with all the components used.
You can create an empty module to avoid this message
<dom-module id="shared-styles">
  <template>
    <style>
   </style>
</template>
</dom-module>
